add_library(arts_tmatrix STATIC tmatrix.cc)
target_link_libraries(arts_tmatrix PUBLIC rtepack)
target_include_directories(arts_tmatrix PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
if(ENABLE_TMATRIX)
  target_link_libraries(arts_tmatrix PRIVATE tmatrix)
  target_compile_definitions(arts_tmatrix PRIVATE ARTS_HAS_TMATRIX=1)
  if(ENABLE_TMATRIX_QUAD)
    target_compile_definitions(arts_tmatrix PRIVATE ARTS_TMATRIX_QUAD=1)
  endif()
endif()
